name: "Automated Code Review with Philips OpenAI API"
description: "Run an automated code review on pull requests using Philips OpenAI API and post comments to PR."

inputs:
  GITHUB_TOKEN:
    description: "GitHub token to authenticate the API requests"
    required: true
  GITHUB_REPOSITORY:
    description: "GitHub repository name (e.g., owner/repo)"
    required: true
  PR_NUMBER:
    description: "Pull request number"
    required: true
  DEX_USERNAME:
    description: "Dex Username"
    required: true
  DEX_PASSWORD:
    description: "Dex Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      shell: bash
      run: |
        python --version
        python -m venv venv
        source venv/bin/activate
        pip install selenium requests webdriver-manager

    - name: Run get_cookies_selenium.py and code_review.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        DEX_USERNAME: ${{ inputs.DEX_USERNAME }}
        DEX_PASSWORD: ${{ inputs.DEX_PASSWORD }}
        GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
        GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        python ${{ github.action_path }}/script/get_cookies_selenium.py
